integralfamilies:


  - name: "topo235"
    loop_momenta: [ r1, r2, r3]
    propagators:
     - [ " r1 ", 0]
     - [ " r2 ", 0]
     - [ " r3 ", 0]
     - [ " p1+p2+r1+r2+r3 ", m2]
     - { bilinear: [ [" p1 + p2 + r1 + r2 + r3","-p1 + u*p2"], 0 ] }
     - [ " p1 + r1 ", 0]
     - [ " p2 + r3 ", 0]
     - [ " r1 + r2 ", 0]
     - [ " r1 + r3 ", 0]
     - [ " p1 + r1 + r3 ", 0]
     - [ " p2 + r1 + r3 ", 0]
     - [ " p2 + r1 + r2 + r3 ", 0]
    cut_propagators: [1,2,3,4,5]
