kinematics:
 incoming_momenta: [p1,p2,p3]
 outgoing_momenta: []
 momentum_conservation: [p3, -p1-p2]
 kinematic_invariants:
  - [m2,2]
  - [s12,2]
  - [u, 0]
 scalarproduct_rules:
  - [[p1,p1], 0]
  - [[p2,p2], 0]
  - [[p1,p2], s12/2]
 symbol_to_replace_by_one: m2